# Generated by Django 5.2.10 on 2026-02-01 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="page_data",
            new_name="page_date",
        ),
    ]
