# Generated by Django 5.2.10 on 2026-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_rename_page_data_page_page_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="diary/picture/", verbose_name="写真"
            ),
        ),
    ]
